### ISSUE TITLE
Excerpt is not migrated

### ISSUE THREAD

**Issue by jashsayani** [hexojs/hexo-migrator-wordpress#33]
I use the "Read more…" tags a lot on my Wordpress blog. When I migrate the posts to hexo, the tags are not moved over from the xml file.

Tags in wordpress export:
`<!--more-->`

Expected tag in hexo markdown (MISSING):
`<!-- more -->`

I am using hexo-migrator-wordpress 1.0.0

**Comment by curbengh** [comment]
That is an excerpt or description of the post. It's possible to fix https://github.com/hexojs/hexo-migrator-rss/issues/41

But still, if I can have a sample XML (https://github.com/hexojs/hexo-migrator-wordpress/issues/54), it can help me to verify that the excerpt is imported correctly.

**Comment by adnan360** [comment]
@curbengh
An implementation of that would really help me. Here is a test export (zipped):
[test.WordPress.2020-06-26.xml.zip](https://github.com/hexojs/hexo-migrator-wordpress/files/4836745/test.WordPress.2020-06-26.xml.zip)

- I just installed wordpress and put more tags into the default post and pages (done with latest Gutenberg editor).
- Furthermore, I installed the Classic Editor plugin and then created a test post titled "Classic Post" with the classic editor to test how it affects the export.
- Then exported it from WP Admin - Tools - Export - All content - Download Export File.
- WordPress was 5.4.2, all updates installed.

**== In XML exports:**

It seems classic editor puts:
```
<!--more-->
```

And Gutenberg editor puts (including block tags):
```
<!-- wp:more -->
<!--more-->
<!-- /wp:more -->
```

**== After migration:**

My migration plugin was at `1.0.0`.

`hello-world.md` (Hello World post) has:
```
---
title: Hello world!
url: 1.html
id: 1
categories:
  - Uncategorized
date: 2020-06-26 10:34:42
tags:
---

Welcome to WordPress. This is your first post. Edit or delete it, then start writing!

This is some text after the more tag.
```

There is no **more** tag anywhere.

`classic-post.md` (Classic Post written in Classic editor) has:
```
---
title: Classic Post
url: 9.html
id: 9
categories:
  - Uncategorized
date: 2020-06-26 11:01:34
tags:
---

This is a test excerpt before the more tag edited in Classic Editor. This is some content after the more tag. This will be some more content for test.
```

There is no **more** tag and the content after more tag has been merged with the line before it.

**Comment by curbengh** [comment]
@adnan360 

Thanks for the attachment, it's good to have Gutenberg version.

May I know which _tag_ are you referring?

``` diff
---
title: Classic Post
+tags:
---
```

or

```
<!--more-->
```

**Comment by adnan360** [comment]
> May I know which _tag_ are you referring?

I was referring to `<!--more-->`

**Comment by adnan360** [comment]
I think there is an issue. Separate posts are created for uploads that show up in Media library. I have also used external <img> tags, but they don't create posts. I'm not sure if it's related to this PR though.

I've [posted](https://github.com/hexojs/hexo-migrator-wordpress/pull/64#issuecomment-653790681) about this, but maybe wasn't fast enough. Posted just some seconds after merging. Sorry I didn't test with images at first. I thought it was a PR for excerpt, so it never occurred to me that this could happen.

A further look into the xml brought me to conclusion that we are somehow taking all `<item>...</item>` elements into consideration. Media uploads are also considered internally as posts, so maybe that's why they are also in the xml as `<item>`s.

```
					<item>
		<title>greens-4926370_640</title>
		<link>http://localhost/wp-hexotest/2020/07/04/post-with-image-classic-editor/greens-4926370_640/</link>
...
		<dc:creator><![CDATA[admin]]></dc:creator>
		<guid isPermaLink="false">http://localhost/wp-hexotest/wp-content/uploads/2020/07/greens-4926370_640.jpg</guid>
...
		<wp:post_type><![CDATA[attachment]]></wp:post_type>
...
</item
```

We'll have to ignore `<item>`s with `<wp:post_type><![CDATA[attachment]]></wp:post_type>` to create separate posts for them.

**Comment by curbengh** [comment]
> We'll have to ignore `<item>` with `<wp:post_type><![CDATA[attachment]]></wp:post_type>` to create separate posts for them.

Thanks for the insight. The zip file that you attached can be useful in tackling https://github.com/hexojs/hexo-migrator-wordpress/issues/37.
