### ISSUE TITLE
paragraphs lost post-migration

### ISSUE THREAD

**Issue by jashsayani** [hexojs/hexo-migrator-wordpress#35]
My wordpress export file has posts which contain multiple paragraphs (there are some new lines after a paragraph), but the migrated markdown loses the paragraphs.

**Comment by curbengh** [comment]
Can you attach a sample xml file? I'm planning to rewrite this plugin.

**Comment by curbengh** [comment]
I can confirm this issue using the Wordpress XML provided by https://github.com/hexojs/hexo-migrator-wordpress/pull/64#issuecomment-653790681.

This issue happens when WP classic editor is used, but not in modern editor (Guternberg). New line is somehow removed by [turndown](https://github.com/domchristie/turndown). I'll see if there is any option to tweak.

**Comment by jashsayani** [comment]
> Can you attach a sample xml file? I'm planning to rewrite this plugin.

Attached. 


[jashsblog.WordPress.2020-07-25.xml.zip](https://github.com/hexojs/hexo-migrator-wordpress/files/4974925/jashsblog.WordPress.2020-07-25.xml.zip)

**Comment by curbengh** [comment]
Thank you. It confirms my suspicion that the exported post doesn't have `<p>`. To be fixed in https://github.com/hexojs/hexo-migrator-wordpress/pull/79.

**Comment by jashsayani** [comment]
thank you for verifying! I assume it will be in 2.1.0
