### ISSUE TITLE
Sample Wordpress XML required

### ISSUE THREAD

**Issue by curbengh** [hexojs/hexo-migrator-wordpress#54]
I recently did a major rewrite on [hexo-migrator-rss](https://github.com/hexojs/hexo-migrator-rss/pull/34) and I'm interested in updating this plugin as well.

However, I've never used Wordpress so I'm not familiar with the XML export. There might be a documentation on its XML structure somewhere, but even if I could create a dummy blog, that doesn't necessarily cover sufficient use case.

This is an appeal for anyone who is/was actively using Wordpress v5, I would like to request for a production-grade exported XML. This can significantly help me to cover the necessary use cases and more importantly to have unit tests for this plugin.

**Comment by SukkaW** [comment]
[WordPress.2020-01-05.xml.txt](https://github.com/hexojs/hexo-migrator-wordpress/files/4023307/WordPress.2020-01-05.xml.txt)

A export file from WordPress 5.2.4, running on a WordPress online demo: https://s1.demo.opensourcecms.com/wordpress/.

**Comment by curbengh** [comment]
Appreciate it. But all the posts don't have tag/category though, so I can't fix https://github.com/hexojs/hexo-migrator-wordpress/issues/36.

**Comment by SukkaW** [comment]
@curbengh 

Open Source CMS has provided the free online WordPress Demo: https://s1.demo.opensourcecms.com/wordpress/

Login info can be found at: https://www.opensourcecms.com/wordpress/

**Comment by jehy** [comment]
Still needed? I can send a fresh one.

**Comment by curbengh** [comment]
Do you have a post with more than two tags/categories? I still need one for https://github.com/hexojs/hexo-migrator-wordpress/issues/36.

**Comment by jehy** [comment]
Yeah, here you go, it's a post with three tags.
```xml
<item>
		<title><![CDATA[Анти-вконтакти]]></title>
		<link>https://jehy.ru/articles/2008/08/22/anti-vkontakte/</link>
		<pubDate>Fri, 22 Aug 2008 13:32:00 +0000</pubDate>
		<dc:creator><![CDATA[jehy]]></dc:creator>
		<guid isPermaLink="false">http://localhost/jehy.ru/articles/archives/240/%d0%b0%d0%bd%d1%82%d0%b8-%d0%b2%d0%ba%d0%be%d0%bd%d1%82%d0%b0%d0%ba%d1%82%d0%b8</guid>
		<description></description>
		<content:encoded><![CDATA[Bad mood today]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>240</wp:post_id>
		<wp:post_date><![CDATA[2008-08-22 17:32:00]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2008-08-22 13:32:00]]></wp:post_date_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[open]]></wp:ping_status>
		<wp:post_name><![CDATA[anti-vkontakte]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[post]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
										<category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>
		<category domain="post_tag" nicename="%d0%b8%d0%bd%d1%82%d0%b5%d1%80%d0%bd%d0%b5%d1%82%d1%8b"><![CDATA[интернеты]]></category>
		<category domain="post_tag" nicename="%d0%bd%d0%b0%d1%84%d0%b8%d0%ba"><![CDATA[нафик]]></category>
		<category domain="post_tag" nicename="%d1%80%d1%83%d0%b1%d0%b5%d0%b6"><![CDATA[рубеж]]></category>
						<wp:postmeta>
		<wp:meta_key><![CDATA[_edit_last]]></wp:meta_key>
		<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
							<wp:postmeta>
		<wp:meta_key><![CDATA[_wp_old_slug]]></wp:meta_key>
		<wp:meta_value><![CDATA[%d0%b0%d0%bd%d1%82%d0%b8-%d0%b2%d0%ba%d0%be%d0%bd%d1%82%d0%b0%d0%ba%d1%82%d0%b8]]></wp:meta_value>
		</wp:postmeta>
							</item>
```

**Comment by curbengh** [comment]
Thanks. Do you know WP has [*nested*](https://hexo.io/docs/front-matter#Categories-amp-Tags) category?
For example, a hexo post has the following front-matter:

``` yml
categories:
- foo
- bar
```

Then that post will be listed in http://myhexo.com/categories/foo/ and http://myhexo.com/categories/foo/bar/. I wonder if I should import WP category as tags instead (which is not nested).

**Comment by jehy** [comment]
I suppose we should
1) have option to ignore categories (helps in cases like https://github.com/hexojs/hexo-migrator-wordpress/issues/74) 
2) When using nested categories, we should join them and make into tags, so `foo/bar and foo/bar2` should became tags `foo-bar` and `foo-bar2`.

**Comment by curbengh** [comment]
and a third option for retaining nested categories. I'm okay with all these options, but if WP doesn't support nested categories in the first place, then perhaps nested shouldn't be default here.

I'm thinking of other available options.
Does WP supports tags? Like http://mywp.com/tags/foo
Can user choose to make `categories` (set in editor) to appear as `tags`?
Does WP supports both categories and tags?

**Comment by jehy** [comment]
> but if WP doesn't support nested categories

Nested categories are supported in WP out of box.

> Does WP supports tags? Like http://mywp.com/tags/foo

Yes, in my sample XML `<category domain="post_tag"` are tags.

> Does WP supports both categories and tags at a same time?

Yes.

> Can user choose to make categories (set in editor) to appear as tags?

No. Categories and tags are different entities, but to put it simply - the only difference is that tags aren't nested.

**Comment by curbengh** [comment]
> Nested categories are supported in WP out of box.
Is it the default behavior? If I set categories as "foo" & "bar", then it will be nested as "foo" and "foo/bar"?. Can I override it not to be nested?

> `category domain="post_tag` are tags
I didn't notice that, since v2, all categories and tags are imported as tags. time to fix...

**Comment by adnan360** [comment]
@curbengh

> Is it the default behavior? If I set categories as "foo" & "bar", then it will be nested as "foo" and "foo/bar"?. Can I override it not to be nested?

Well, I was surprised when I faced issue #35 on my import. WordPress is way different in assigning categories than Hexo. I'm not used to such kind of categorizing. Let me ramble a bit about my experience, I had lots of "labels" (like tags) on my Blogger and when I converted to WP it came as tags. But I wanted some to be categories. So I converted some tags into categories. So some posts had multiple categories. But when I converted to Hexo, it showed one category inside another (hierarchical).

In WP we are used to assigning multiple categories to post. Those categories can either be all top level or sub categories (as seen [here](https://github.com/hexojs/hexo-migrator-wordpress/issues/36#issuecomment-664003244)). They all show as flat category listed on post page. But Hexo expects multiple categories to be inside one another! I tried many workarounds, but none worked.

Then I found [this discussion](https://github.com/hexojs/hexo/issues/848) which points out that Hexo community doesn't like non-hierarchical categories. Multiple categories absolutely must have to be hierarchical. :-) 

For example, if I even add this as suggested by @jashsayani [here](https://github.com/hexojs/hexo-migrator-wordpress/issues/36#issue-383459444):
```
categories:
  - [Featured]
  - [Tutorial]
```
It still shows hierarchical categories:
![wp-hierar-cat-01](https://user-images.githubusercontent.com/7857310/88483440-c7eeb300-cf89-11ea-9e25-80fd34f31d33.png)

I found no other way but to keep my tags as tags and continue, because I have posts that belong to multiple categories. So I can't have the categories the way Hexo categories are designed.

**Comment by curbengh** [comment]
> ![](https://user-images.githubusercontent.com/7857310/88483440-c7eeb300-cf89-11ea-9e25-80fd34f31d33.png)

The theme displays it as nested, but if you check the `Tutorial` link, it should be `http://yourhexo.com/categories/tutorial`, not `http://yourhexo.com/categories/featured/tutorial`. Perhaps a theme couldn't differentiate whether a category is nested or not, but that's a separate issue.

**Comment by adnan360** [comment]
I have shared exports from time to time, but the problem is that the localhost image url references cause issues for others when importing. I think having an online wordpress site would help the development.

There are many [free wp hosts](https://smartblogger.com/free-wordpress-hosting/) out there that I think would be perfect for this. I have my eyes on AwardSpace (although I haven't used it before). Many has 1 click installer which would be convenient. Although backup of the site should be kept handy because sometimes these free hosts terminate accounts for many reasons.

You can create test posts there, export it, have it as gist for everyone to test. We can then use the raw url of that gist for our tests. This way the tests can be streamlined.

**Comment by curbengh** [comment]
I agree with having a testbed, though I'm not so keen on free hosts as I find them a bit dodgy. After v2.1.0, I plan to create a VM with a dummy WP in my local machine. VPS hosting like DigitalOcean and Linode also offer 1-click installer and having it up for a few days (for testing) only cost a few cents.
